title: Data Structures + Blockchain Project
description: Educational docs for a simple UTXO-based blockchain with mempool DAG and mining
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: GFM
show_downloads: false
github:
  is_project_page: true

url: "https://swimmingrieux.github.io"
baseurl: "/DS-Blockchain"

collections:
  fa:
    output: true
    permalink: /:collection/:path
